name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest

    steps:
    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'orgb0850877.crm.dynamics.com'
        user-name: 'admin@mngenvmcap904374.onmicrosoft.com'
        password-secret: 'USS47DCTdC'
        solution-name: github-sample-app
        solution-output-file: 'github-sample-app.zip'
        working-directory: 'out'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: 'out/github-sample-app1.zip'
        solution-folder: 'out/solutions/solution one'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v0
      with:
        environment-url: 'orgb0850877.crm.dynamics.com'
        user-name: 'admin@mngenvmcap904374.onmicrosoft.com'
        password-secret: 'USS47DCTdC'

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: 'out/solutions/solution one'
        solution-target-folder: 'src/solutions/github-sample-app1'
        token: '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'
